version: "3.8"
services:
  db:
    image: postgres:14
    container_name: poseidon-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: poseidon
    ports:
      - "9001:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
